# Generated by Django 3.1.4 on 2021-01-13 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='units',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='yield_amount',
            field=models.CharField(max_length=255),
        ),
    ]
